In [1]:
import pandas as pd
import zipfile
import os

def concatenate_zips(folder_path):
    all_dataframes = []

    # Loop through every file in the directory
    for filename in os.listdir(folder_path):
        if filename.endswith(".zip"):
            file_path = os.path.join(folder_path, filename)
            #Crawl through directory a
            with zipfile.ZipFile(file_path, 'r') as z:
                for internal_file in z.namelist():
                    if internal_file.endswith(".csv"):
                        with z.open(internal_file) as f:
                            df = pd.read_csv(f)
                            df['source_file'] = filename
                            all_dataframes.append(df)
    
    if all_dataframes:
        master_df = pd.concat(all_dataframes, ignore_index=True)
        return master_df
    else:
        print("No CSV files found in the ZIPs.")
        return None

# Usage
# folder_to_scan = './my_data_folder'
# final_df = concatenate_zips(folder_to_scan)

In [ ]:
#Load main Data Table
full_dataframe = concatenate_zips("C:\\Users\\cadek\\OneDrive\\Desktop\\CSC881 (Data Mining)\\Project\\Flight Data")

C:\Users\cadek\AppData\Local\Temp\ipykernel_32276\3610890433.py:17: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)

In [ ]:
#Load Lookup Table
airport_lookup = pd.read_csv("C:\\Users\\cadek\\OneDrive\\Desktop\\CSC881 (Data Mining)\\Project\\Data Lookup Tables\\T_MASTER_CORD.csv", index_col="Code")
carrier_lookup = pd.read_csv("C:\\Users\\cadek\\OneDrive\\Desktop\\CSC881 (Data Mining)\\Project\\Data Lookup Tables\\Carriers.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\cadek\\OneDrive\\Desktop\\CSC881 (Data Mining)\\Project\\Data Lookup Tables\\T_MASTER_COORD.csv'

In [9]:
full_dataframe.head()

,YEAR,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,OP_CARRIER,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,...,DIVERTED,AIR_TIME,FLIGHTS,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,source_file
0,2024,1/1/2024 12:00:00 AM,9E,20363,9E,N131EV,5225.0,10397,1039707,30397,...,0.0,33.0,1.0,164.0,NaN,NaN,NaN,NaN,NaN,T_ONTIME_MARKETING_20260320_190717.zip
1,2024,1/1/2024 12:00:00 AM,9E,20363,9E,N132EV,5115.0,11433,1143302,31295,...,0.0,89.0,1.0,651.0,NaN,NaN,NaN,NaN,NaN,T_ONTIME_MARKETING_20260320_190717.zip
2,2024,1/1/2024 12:00:00 AM,9E,20363,9E,N132EV,5414.0,11423,1142308,31423,...,0.0,87.0,1.0,533.0,NaN,NaN,NaN,NaN,NaN,T_ONTIME_MARKETING_20260320_190717.zip
3,2024,1/1/2024 12:00:00 AM,9E,20363,9E,N133EV,5284.0,12953,1295304,31703,...,0.0,103.0,1.0,722.0,NaN,NaN,NaN,NaN,NaN,T_ONTIME_MARKETING_20260320_190717.zip
4,2024,1/1/2024 12:00:00 AM,9E,20363,9E,N133EV,5341.0,10994,1099402,30994,...,0.0,83.0,1.0,641.0,NaN,NaN,NaN,NaN,NaN,T_ONTIME_MARKETING_20260320_190717.zip

In [ ]:
print(type(dest_counts['AIRPORT_ID'].iloc[0]))
print(type(airport_lookup.index[0]))

KeyError: 'T_MASTER_COORD'

In [21]:
#Find top 100 airports
dest_counts = full_dataframe['DEST_AIRPORT_ID'].value_counts().reset_index()
dest_counts.columns = ['AIRPORT_ID', 'FLIGHT_COUNT']
dest_counts.head(100)

dest_counts['AIRPORT_ID'] = dest_counts['AIRPORT_ID'].astype(int)

dest_data = pd.merge(
    dest_counts, 
    airport_lookup, 
    left_on='AIRPORT_ID', 
    right_on='Code', # Use 'Code' if it's a column, or right_index=True if it's the index
    how='left'
).drop(columns=["Code"])

dest_data.head(100)

,AIRPORT_ID,FLIGHT_COUNT,Description
0,10397,342557,"Atlanta, GA: Hartsfield-Jackson Atlanta Intern..."
1,13930,318122,"Chicago, IL: Chicago O'Hare International"
2,11298,315680,"Dallas/Fort Worth, TX: Dallas/Fort Worth Inter..."
3,11292,313280,"Denver, CO: Denver International"
4,11057,252408,"Charlotte, NC: Charlotte Douglas International"
...,...,...,...
95,11109,12969,"Colorado Springs, CO: City of Colorado Springs..."
96,14321,12687,"Portland, ME: Portland International Jetport"
97,12217,12428,"Huntsville, AL: Huntsville International-Carl ..."
98,12197,12332,"White Plains, NY: Westchester County"
99,11638,12004,"Fresno, CA: Fresno Yosemite International"